### ISSUE TITLE
VulnerabilityService GetAllForProject doesn't allow control of suppressed

### ISSUE THREAD

**Issue by duanemay** [DependencyTrack/client-go#9]
I have added this feature to my code, and would like to contribute the change. In other places you have a bool passed to the function to control the inclusion of suppressed issues or not. I see 3 options, and would like to determine the best path forward to make a PR:

1. add a flag to GetAllForProject
   Breaking change: Adding this flag is easy, but will require users to update their code to be compatible.

2. add a new func
The current func is called `GetAllForProject` but only returns the non-suppressed. What is a good name here?
`GetAllForProjectIncludingSuppressed`

3. add optional `...` request options to the end of the param list, that could be used to pass a params object
  requires no change to existing code, 
  keeps the name `GetAllForProject`
  does not match the existing code style

**Comment by nscuro** [comment]
Hey @duanemay, appreciate you raising an issue to discuss options.

IMO all options would be fine-ish, but I prefer the first one. That is, making this a breaking change.

I don't think it's worth to "bend over backwards" here to avoid breaking changes at all cost. It's a very small change after all, and the module is still versioned as `v0`.

While you're at it, could you apply the same change to `GetAllForComponent`, too?

https://github.com/DependencyTrack/client-go/blob/1e317861ea98fadd51ee9991ed92e6acc87d1219/vulnerability.go#L76
